# DB 연결 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://{private-ip}:3306/wanted_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username={db-username}
spring.datasource.password={db-password}

# JPA 설정 (테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


management.endpoints.web.exposure.include=metrics,prometheus,health
management.metrics.export.datadog.apiKey={api-key}
management.metrics.export.datadog.uri=https://api.ap1.datadoghq.com
management.metrics.export.datadog.enabled=true
spring.datasource.hikari.pool-name=HikariPool-1
